// types.js
/*
export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGOUT_USER_COMPLETE = 'LOGOUT_USER_COMPLETE';
export const SET_USER_INFO = 'SET_USER_INFO';


// Forgot password
export const FORGOT_PASSWORD_EMAIL_SENT = 'FORGOT_PASSWORD_EMAIL_SENT';
export const FORGOT_PASSWORD_EMAIL_NOT_SENT = 'FORGOT_PASSWORD_EMAIL_NOT_SENT';
export const RESET_PASSWORD_COMPLETE = 'RESET_PASSWORD_COMPLETE'; */
